Repository philjdelong/dev.to, pull requests merged in 2020-03, with the labels that each got.

#16 Ali/reading collection/index
  app/controllers/reading_list_items_controller.rb
  app/models/article.rb
  app/models/reading_collection.rb
  app/models/reading_collection_article.rb
  app/models/user.rb
  app/services/users/delete.rb
  app/views/reading_list_items/index.html.erb
  db/migrate/20200323220100_create_reading_collections.rb
  db/migrate/20200323220842_create_reading_collection_articles.rb
  db/schema.rb
  spec/factories/reading_collections.rb
  spec/models/article_spec.rb
  spec/models/reading_collection_article_spec.rb
  spec/models/reading_collection_spec.rb
  spec/models/user_spec.rb
  spec/requests/reading_list_items_spec.rb
Labels: BE Chore, Collection Index

#23 Ali/collection show
  app/controllers/reading_collections_controller.rb
  app/controllers/reading_list_items_controller.rb
  app/models/reading_collection.rb
  app/views/reading_collections/show.html.erb
  config/routes.rb
  db/migrate/20200326231610_add_slug_to_reading_collections.rb
  db/migrate/20200327020008_add_index_on_slug_reading_collection.rb
  db/schema.rb
  spec/models/reading_collection_spec.rb
  spec/system/reading_collections/user_visits_a_collection_spec.rb
Labels: BE Chore, Collection Show, Final Sprint

#29 Add new collection form & display
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/preact/article-form.scss
  app/controllers/api/v0/reading_collections_controller.rb
  app/javascript/packs/collectionForm.jsx
  app/javascript/readingList/__tests__/__snapshots__/collectionForm.test.jsx.snap
  app/javascript/readingList/__tests__/__snapshots__/collectionList.test.jsx.snap
  app/javascript/readingList/__tests__/__snapshots__/readingList.test.jsx.snap
  app/javascript/readingList/__tests__/collectionForm.test.jsx
  app/javascript/readingList/collectionForm.jsx
  app/javascript/readingList/collectionList.jsx
  app/views/reading_collections/_new.html.erb
  app/views/reading_collections/new.html.erb
  app/views/reading_list_items/index.html.erb
Labels: FE Chore, enhancement

#32 Fe refactor
  app/javascript/readingList/collectionArticles.jsx
  app/javascript/readingList/collectionForm.jsx
  app/javascript/readingList/collectionList.jsx
  app/javascript/readingList/components/Article.jsx
  app/javascript/readingList/components/Collection.jsx
  app/javascript/readingList/components/tagDisplay.jsx
Labels: FE Chore

#33 Ali/worker bug fixes
  app/controllers/reading_collections_controller.rb
  app/models/reading_collection.rb
  app/workers/reading_collections/refresh_reading_collection_worker.rb
  spec/requests/reading_collections/show_spec.rb
  spec/workers/reading_collections/refresh_collection_worker_spec.rb
  spec/workers/reading_collections/refresh_reading_collection_worker_spec.rb
Labels: Final Sprint, bug

#34 Fe refactor
  app/assets/stylesheets/articles.scss
  app/javascript/readingList/__tests__/__snapshots__/collectionArticles.test.jsx.snap
  app/javascript/readingList/__tests__/__snapshots__/collectionForm.test.jsx.snap
  app/javascript/readingList/__tests__/__snapshots__/collectionList.test.jsx.snap
  app/javascript/readingList/__tests__/__snapshots__/readingList.test.jsx.snap
  app/javascript/readingList/__tests__/collectionArticles.test.jsx
  app/javascript/readingList/__tests__/collectionForm.test.jsx
  app/javascript/readingList/__tests__/collectionList.test.jsx
  app/javascript/readingList/__tests__/readingList.test.jsx
  app/javascript/readingList/collectionForm.jsx
  app/javascript/readingList/collectionList.jsx
  app/javascript/readingList/components/Article.jsx
  app/javascript/readingList/mocks/mockTestData.js
  app/views/reading_collections/new.html.erb
Labels: FE Chore
